In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a
print(a)

[1 2 3]


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.shape
b.shape


(2, 3)

In [7]:
a.shape

(3,)

In [8]:
b.shape


(2, 3)

In [9]:
a.dtype

dtype('int64')

In [10]:
b.dtype

dtype('int64')

In [11]:
a.itemsize

8

In [14]:
b.itemsize

8

In [15]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
a.shape


(2, 5)

In [17]:
a[1, 2]

np.int64(8)

In [18]:
print(a[0, 0])

1


In [19]:
print(a[0, :])

[1 2 3 4 5]


In [20]:
print(a[1: :])

[[ 6  7  8  9 10]]


In [21]:
print(a[:, 2])

[3 8]


In [22]:
a[0,3]=4
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
a[0,3]=-2
print(a)

[[ 1  2  3 -2  5]
 [ 6  7  8  9 10]]


In [25]:
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
